### ISSUE TITLE
Is this project still maintained and in sync with the Chrome extension?

### ISSUE THREAD

**Issue by prascuna** [callumlocke/json-formatter#179]
Hi,
I'm a bit confused: The  [Chrome extension](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa/related?hl=en-GB) has been updated in May 2021 with version `0.6.0` but I can't find the source for this version here on github.
Has the official repo been moved somewhere else?

**Comment by callumlocke** [comment]
Hi @prascuna and other understandably concerned people...

- **Yes** it's still in sync with the extension on the [Chrome Store](https://chrome.google.com/webstore/detail/json-formatter/bcjindcccaagfpapjjmafapmmgkkhgoa). 
- It's not exactly 'maintained' (it last changed 7 years ago) but I still control it and it still seems to work fine for >99% of users.
- Why is the version number different to that shown on the Store? Think I must have forgotten to push the version tag to GitHub when I last did a release 7 years ago, i.e. currently `master === 0.6.0`.
- Why does the store say it was updated in May 2021? I think Google asked me to provide a privacy statement around then, via a web form, and this must have updated the date on the Store page. The code itself hasn't changed since 2015, I believe.
- At some point I hope to get round to cleaning up this project (get the code building again, close some PRs/issues and do a new release) but bare in mind I earn nothing from this extension, I just made it for myself many years ago and it got popular. The code looks weird af to me now. 
- I am the only person who can publish updates to the Store. I will never let this extension become malware, my name is on it.
