### ISSUE TITLE
Failing with error "Cannot read properties of null"

### ISSUE THREAD

**Issue by lancekuttner** [callumlocke/json-formatter#194]
I am running Chrome Version 100.0.4896.60 (Official Build) (64-bit)
I noticed that just a few hours ago the extension stopped working. The console shows the following error:

Error in event handler: TypeError: Cannot read properties of null (reading 'setAttribute')
    at chrome-extension://bcjindcccaagfpapjjmafapmmgkkhgoa/js/content.js:77:64

**Comment by microparsec** [comment]
I ran into the same issue.

This is due to #191 not checking if the "meta" "color-scheme" property is actually set or exists, which is not the case on many browsers, and trying to invoke setAttribute on it anyway.

![image](https://user-images.githubusercontent.com/15816341/168325873-e8c52dbb-dc7e-41bc-88da-41a4a35c8e27.png)

**Comment by VR6R** [comment]
I had this issue as well on chrome version 100.0.4896, but just updated to 101.0.4951.67 and it is resolved.

**Comment by jakauppila** [comment]
I'm also encountering this issue with Microsoft Edge `100.0.1185.44 (Official build) (64-bit)`

**Comment by liguobao** [comment]
Me Too

**Comment by asch3ron** [comment]
Same issue here.

**Comment by wommy** [comment]
just submitted a PR https://github.com/callumlocke/json-formatter/pull/195

fixes it for me

**Comment by callumlocke** [comment]
Now fixed in v0.6.2
