### ISSUE TITLE
Can I use JSON formatter to format a response when it is not has 'application/json' as content type in HTTP response?

### ISSUE THREAD

**Issue by n179911** [callumlocke/json-formatter#54]
Hi,

Is it possible to use json-formatter to format a json response but the content type is not set to 'application/json' in the HTTP response?

**Comment by callumlocke** [comment]
It should work with any 'plain text' kind of content-type... So you can use `text/plain` or even something like `application/javascript` or `text/css`. Basically, it has to be the kind of response that would usually make the browser show the content in a monospaced font (instead of the usual Arial or whatever).

If you are stuck serving your JSON as `text/html`, then one hack is to wrap all the JSON in `<pre>..</pre>`. Surprisingly this triggers the extension (providing it is the only element on the page).

**Comment by n179911** [comment]
Thanks. But I can't modify the content-type or what the server send to me. How can I wrap the JSON respoinse in <pre>../</pre> tag?

**Comment by callumlocke** [comment]
ah if you don't control the server at all then you're stuck. you'll need to be able to modify the server's response before it gets to the browser, either by setting the correct content type header (application/json) or wrapping the whole response body in pre tags. if it's a third party server that is configured wrongly, and you don't have access, all you can do is ask them to fix it by setting the correct content type

**Comment by eschwartz** [comment]
What would you think about having some way to manually trigger the formatter? For example, an item in the context menu *"Format as JSON"*

**Comment by cja-github** [comment]
Please just make it so that I can press the plugin toolbar button to make it format the displayed data as JSON.

I'm sure you've written very clever code to try to detect JSON, but it's clearly imperfect so this would save you and users a lot of hassle.
